# Change these first
owner: WindsorWu # Your GitHub organization or username, where this repository lives
repo: uptimemonitor.github.io # The name of this repository

sites:
  - name: WindsorWu's Index
    url: https://www.nekolin.top
  - name: WindsorWu's Blog
    url: https://blog.nekolin.top

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: statusnekolin.top
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Nekolin Upptime
  introTitle: "**Nekolin Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: Blog
      href: https://blog.nekolin.top

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
