# Change these first
owner: WindsorWu # Your GitHub organization or username, where this repository lives
repo: uptimemonitor.github.io # The name of this repository

sites:
  - name: Index
    url: https://www.nekolin.top
  - name: WindsorWu's Blog
    url: https://blog.nekolin.top

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.nekolin.top
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: 喵酱小林网站监控
  introTitle: "**喵酱小林网站监控** 是开源的数据监测收集网站, 完全依赖于Github运行."
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: Blog
      href: https://blog.nekolin.top

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
